baseURL: https://blog.flyfriend.eu.org/
languageCode: en-us
title: Flyfriend Blog
theme: mini
paginate: 3


hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: 
disqusShortname: 


markup:
  highlight:
    guessSyntax: true
    style: emacs


social:
  github: https://github.com/Flyfriend
  twitter: 
  stackoverflow: 


params:
  author: Flyfriend
  bio: Three ambitious youngsters
  description: Our Blog
  enableRSS: true
  enableComments: true
  enableGoogleAnalytics: false
