theme = "simple-blog"
baseURL = "https://blog.flyfriend.eu.org/"
title = "Flyfriends Offical"
copyright = "© 2020-2021 Copyright Flyfriends."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"

[params]
description = "Sky isn't impossible."